### ISSUE TITLE
Thoughts while hacking with Malwoden from the video tutorial writer

### ISSUE THREAD

**Issue by Rakaneth** [Aedalus/malwoden#68]
As I hack on a prototype roguelike, here are some things I would like to see:

* More dungeon-generating algorithms. While I've instituted a rule for this particular project that I cannot use rot-js, I've been tempted to break it on a couple of occasions. 
* A few more features of the `Util.Rect` utility class. I rolled my own in my project to use with a basic BSP dungeon generator.
* a method to clear a `Util.Table`
* [Dijkstra maps](http://www.roguebasin.com/index.php?title=The_Incredible_Power_of_Dijkstra_Maps) - I prefer these to traditional A* pathfinding, esp. for fleeing monsters. I might try rolling my own using `Util.Table`.
* More/better documentation! I've had to do some code diving in some cases to figure out how things worked, but I am willing to let this pass for an alpha. As a stark example, I decided to look at the mouse example just before submitting this and found that one of the things I thought was missing - capturing mouse movement without a click - is actually implemented! I would not have known if I hadn't looked at the example source.

None of these things have been showstoppers so far. While I've had to roll my own BSP generator (I was actually grateful for the exercise), the library has been straightforward to work with.

**Comment by Rakaneth** [comment]
Another thought - a way to print wrapped text in a `Terminal` would be nice for writing message logs. I could step out of the canvas and use standard JS/HTML for this, though.

**Comment by Aedalus** [comment]
I appreciate the feedback on the library! Been caught up with work the past couple months, but hoping to start working on some of the above in the near future. More dungeon-generating algorithms is at the top of my list. Also hoping to get a small tutorial section to the site that might show some more of the basic features that aren't as explicit in the examples.

Thanks for trying out Malwoden, and definitely feel free to leave more thoughts as you have them.

**Comment by Rakaneth** [comment]
I would love a way to respond to _any_ key, and pass the current keys pressed to an event rather than having to write a callback for each individual keycode.

**Comment by Rakaneth** [comment]
Here is a tech demo/prototype I've been tinkering with on and off for the past few months.

https://github.com/Rakaneth/malwoden-test

**Comment by Aedalus** [comment]
Tried to add several of the above changes to the upcoming 0.5.0 release, including Rect/Table improvements, a standardized dungeon-gen interface for future map-gen, and better ways to listen for any keyCode being pressed rather than individual ones. Going to close this issue for now, but appreciate the feedback on the library!
