### ISSUE TITLE
Things that DEFINITELY need documenting

### ISSUE THREAD

**Issue by Rakaneth** [Aedalus/malwoden#72]
I would like to keep a list of things here that DEFINITELY need documenting that I've discovered the hard way.

# Rand module #
 * `AleaRNG.nextInt(min, max)` is **exclusive** on `max`. (I have a bunch of off-by-one errors I think I now need to fix in my prototype.)

**Comment by Aedalus** [comment]
Recently added additional JSDocs around this which should be in the 0.5.0 release, closing for now. Appreciate you bringing this up!
